(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/ENUM' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE SelectorSubStatus : (SelectorSubStatusNormal:=0, SelectorSubStatusChangePos, SelectorSubStatusRefStopped, SelectorSubStatusRefAlarm,
								SelectorSubStatusAlarm, SelectorSubStatusTimeout, SelectorSubStatusConfErr, SelectorSubStatusUnknownCommand,
								SelectorSubStatusBadCommandParameter);
END_TYPE
(* @END_DECLARATION := '0' *)
